environment:
  matrix:
    - PWSH_RELEASE: native
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
    - PWSH_RELEASE: stable
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
    - PWSH_RELEASE: preview
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
    - PWSH_RELEASE: stable
      APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu
    - PWSH_RELEASE: preview
      APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu

test: off
  
build_script:
  - ps: .\appveyor.ps1
